################
#  EnvEndpoint #
################

target.homepage=http://automationexercise.com/login


################
#  Account     #
################
account.username=testminu1111@gmail.com
account.password=Minu@123
########
################
account.username_invalid=inapp1
account.password_invalid=inApp@12355
########



path.searchData=src/main/resources/searchData.json
#######

